branch-defaults:
  main:
    environment: rt-palettes-circular-prod
global:
  application_name: rt-palettes-circular-api
  default_ec2_keyname: null
  default_platform: Node.js 18
  default_region: eu-central-1
  profile: null
  sc: git
