branch-defaults:
  default:
    environment: rt-pricing-grids-api-prod
global:
  application_name: rt-pricing-grids-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
